version: '2'

services:
  web:
    build: .
    environment:
     - ENDPOINT_TYPE
     - APP_TYPE
     - JCE_PROVIDER
    cpuset: '0'
  h2load:
    build:
      dockerfile: Dockerfile.h2load
      context: .
